repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-toml
-   repo: local
    hooks:
    -   id: ruff-lint
        name: Ruff Linter
        entry: ruff check src tests --fix
        language: system
        types: [python]
        pass_filenames: false

    -   id: ruff-format
        name: Ruff Formatter
        entry: ruff format src tests
        language: system
        types: [python]
        pass_filenames: false

    -   id: mypy
        name: Mypy
        entry: mypy .
        language: system
        types: [python]
        pass_filenames: false
