repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
-   repo: local
    hooks:
    -   id: ruff-lint
        name: Ruff Linter
        entry: poetry -C packages/executor run ruff check . --fix --exit-non-zero-on-fix
        language: system
        types: [python]
        pass_filenames: false
    -   id: ruff-format
        name: Ruff Formatter
        entry: poetry -C packages/executor run ruff format .
        language: system
        types: [python]
        pass_filenames: false
    -   id: mypy
        name: Mypy
        entry: poetry -C packages/executor run mypy .
        language: system
        types: [python]
        pass_filenames: false
