[project]
name = "teddy"
version = "0.1.0"
description = "TeDDy: Your Contract-First & Test-Driven Pair-Programmer"
authors = [
    {name = "N/A"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = "^3.11"
dependencies = [
    "typer[all] (>=0.20.0,<0.21.0)",
    "pyyaml (>=6.0.3,<7.0.0)",
    "repotree (>=0.1.0,<0.2.0)",
    "pyperclip (>=1.11.0,<2.0.0)",
    "markdownify (>=1.2.2,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.1,<10.0.0)",
    "black (>=25.11.0,<26.0.0)",
    "flake8 (>=7.3.0,<8.0.0)",
    "bandit (>=1.9.1,<2.0.0)",
    "pre-commit (>=4.4.0,<5.0.0)"
]
